using System.Runtime.InteropServices;
using System.Text;
using ChiakiNg.Native;

namespace ChiakiNg.Session;

/// <summary>
/// PP7: the PSN login, minus the browser.
///
/// The Qt client runs the OAuth flow inside a QtWebEngine view - a whole bundled Chromium - and
/// WebView2 replaces the view. What it does NOT replace is everything around it: the authorize URL,
/// the redirect that has to be recognised, the code pulled out of it, and the token request made
/// with it. That is all string work, it is all in this file, and it is where a port breaks
/// silently: a scope spelled differently or a redirect matched slightly wrong is a login that never
/// completes, on a page the user cannot read an error out of.
///
/// So every constant here is held against gui/include/psnaccountid.h by the selftest. Two clients
/// logging in differently is not a thing anyone would report as a port defect.
/// </summary>
public static class PsnAuth
{
    /// <summary>The application this client identifies itself as.</summary>
    public const string ClientId = "ba495a24-818c-472b-b12d-ff231c1b5745";

    /// <summary>
    /// Paired with the id in the Basic header. It is not a secret in any useful sense - it ships
    /// in every copy of the client - and it is here because the endpoint requires it, not because
    /// anything is being protected.
    /// </summary>
    public const string ClientSecret = "mvaiZkRsAsI1IBkY";

    /// <summary>The page the browser lands on when the login is done, carrying the code.</summary>
    public const string RedirectPage = "https://remoteplay.dl.playstation.net/remoteplay/redirect";

    public const string TokenUrl = "https://auth.api.sonyentertainmentnetwork.com/2.0/oauth/token";

    /// <summary>
    /// The four scopes the session needs. One string, spelled exactly, spaces included - it goes
    /// into a URL query and into a form body, and it is the field most likely to be "tidied".
    /// </summary>
    public const string Scope =
        "psn:clientapp referenceDataService:countryConfig.read "
        + "pushNotification:webSocket.desktop.connect sessionManager:remotePlaySession.system.update";

    /// <summary>The authorize URL, before the device id is appended.</summary>
    public const string LoginUrlPrefix =
        "https://auth.api.sonyentertainmentnetwork.com/2.0/oauth/authorize?service_entity=urn:service-entity:psn"
        + "&response_type=code&client_id=" + ClientId
        + "&redirect_uri=" + RedirectPage
        + "&scope=" + Scope
        + "&request_locale=en_US&ui=pr&service_logo=ps&layout_type=popup&smcid=remoteplay"
        + "&prompt=always&PlatformPrivacyWs1=minimal&";

    /// <summary>CHIAKI_DUID_STR_SIZE, read from the shim rather than assumed.</summary>
    public static int DuidSize => DuidStrSize();

    /// <summary>
    /// A client device id, generated by libchiaki. It identifies this installation to the relay,
    /// so it is asked for rather than invented: a Guid of the right shape is not one the relay
    /// recognises.
    /// </summary>
    public static string GenerateDeviceUid()
    {
        var buf = new byte[DuidSize];
        int size = buf.Length;
        int err = GenerateClientDeviceUid(buf, ref size);
        if (err != (int)ChiakiError.Success)
            throw new InvalidOperationException($"chiaki_holepunch_generate_client_device_uid failed: {(ChiakiError)err}.");

        // The size that comes back counts the terminator, which is not part of the string.
        int end = Array.IndexOf(buf, (byte)0);
        return Encoding.UTF8.GetString(buf, 0, end < 0 ? size : end);
    }

    /// <summary>The URL the browser is pointed at, for one device id.</summary>
    public static string LoginUrl(string deviceUid)
    {
        ArgumentNullException.ThrowIfNull(deviceUid);
        return LoginUrlPrefix + "duid=" + deviceUid + "&";
    }

    /// <summary>
    /// Whether a URL the browser navigated to is the one carrying the code.
    ///
    /// A prefix test and not an equality one, because the redirect arrives with the query string
    /// attached - which is the whole point of it.
    /// </summary>
    public static bool IsRedirect(string? url)
        => url is not null && url.StartsWith(RedirectPage, StringComparison.Ordinal);

    /// <summary>
    /// The authorization code out of a redirect, or null when there is none - which is what a
    /// cancelled login looks like, and is not the same as a URL that is not the redirect at all.
    /// </summary>
    public static string? CodeFrom(string url)
    {
        ArgumentNullException.ThrowIfNull(url);
        if (!IsRedirect(url))
            return null;

        int q = url.IndexOf('?', StringComparison.Ordinal);
        if (q < 0)
            return null;

        foreach (string pair in url[(q + 1)..].Split('&', StringSplitOptions.RemoveEmptyEntries))
        {
            int eq = pair.IndexOf('=', StringComparison.Ordinal);
            if (eq > 0 && pair[..eq] == "code")
            {
                string value = Uri.UnescapeDataString(pair[(eq + 1)..]);
                return value.Length == 0 ? null : value;
            }
        }

        return null;
    }

    /// <summary>The form body that exchanges a code for a token.</summary>
    public static string TokenRequestBody(string code)
    {
        ArgumentNullException.ThrowIfNull(code);
        return $"grant_type=authorization_code&code={code}&scope={Scope}&redirect_uri={RedirectPage}&";
    }

    /// <summary>The form body that renews one. Same shape, different grant.</summary>
    public static string RefreshRequestBody(string refreshToken)
    {
        ArgumentNullException.ThrowIfNull(refreshToken);
        return $"grant_type=refresh_token&refresh_token={refreshToken}&scope={Scope}&redirect_uri={RedirectPage}&";
    }

    /// <summary>The Basic header: the id and the secret, joined by a colon and base64'd.</summary>
    public static string BasicAuthHeader()
        => "Basic " + Convert.ToBase64String(Encoding.UTF8.GetBytes($"{ClientId}:{ClientSecret}"));

    [DllImport(ChiakiNative.Library, EntryPoint = "chiaki_shim_duid_str_size",
        CallingConvention = CallingConvention.Cdecl)]
    private static extern int DuidStrSize();

    [DllImport(ChiakiNative.Library, EntryPoint = "chiaki_shim_generate_client_device_uid",
        CallingConvention = CallingConvention.Cdecl)]
    private static extern int GenerateClientDeviceUid(byte[] buf, ref int size);
}
