// GENERATED by scripts/product.mjs on every build. Do not edit.
//
// The figures the copy states, read out of the application's own source rather than typed
// into a sentence. Regenerate with `npm run generate`; the build does it first.

export interface HostFlag {
  /** The flag itself, including its dashes. */
  readonly name: string;
  /** What follows it, or the empty string where nothing does. */
  readonly argument: string;
  /** One line: what running it does, not how. */
  readonly summary: string;
}

/** The application version, from app/ChiakiNg.csproj. */
export const VERSION = "1.10.0";

/** The target framework it builds against, from the same file. */
export const FRAMEWORK = "net10.0-windows";

/** Every flag the host answers, in the order its own list declares them. */
export const HOST_FLAGS: readonly HostFlag[] = [
  {
    "name": "--selftest",
    "argument": "",
    "summary": "run the host's own assertions and exit with the verdict"
  },
  {
    "name": "--recount",
    "argument": "",
    "summary": "check the sizes the backlog states, and print what corrects each"
  },
  {
    "name": "--ratchet",
    "argument": "[id]",
    "summary": "list the shipped tasks no assertion names; with an id, where it is named"
  },
  {
    "name": "--controllers",
    "argument": "",
    "summary": "print what SDL sees, for a pad that is plugged in now"
  },
  {
    "name": "--capture-controller",
    "argument": "",
    "summary": "log presses for twenty seconds; add --analog for the sticks"
  },
  {
    "name": "--analog",
    "argument": "",
    "summary": "with --capture-controller: include the axes, which flood the log"
  },
  {
    "name": "--capture-mapping",
    "argument": "[path]",
    "summary": "render the mapping screen off-screen to a PNG"
  },
  {
    "name": "--map-controller",
    "argument": "",
    "summary": "open the mapping screen against a real pad"
  },
  {
    "name": "--dcomp-demo",
    "argument": "",
    "summary": "show what one window composes, which PP163 is answered by looking at"
  },
  {
    "name": "--topmost",
    "argument": "",
    "summary": "with --dcomp-demo: the control, asking the visual to cover WPF instead"
  },
  {
    "name": "--layers",
    "argument": "",
    "summary": "with --dcomp-demo: the overlay PP319 chose, over the video plane"
  }
];
